name: poll_availability
description: allow to save and change information about poll availability
author: bgoncharuck
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  json_annotation: ^3.0.1
  
dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
