name: algorithm
description: separate module for calculations
author: bgoncharuck
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  
  int_datetime:
    path: ../int_datetime

  users_repository:
    path: ../data/abstract/users_repository
  userpoll:
    path: ../data/abstract/userpoll
  polls_repository:
    path: ../data/abstract/polls_repository

  prophecy_model:
    path: ../models/prophecy_model
  prophecies:
    path: ../data/abstract/prophecies
