name: algorithm
description: separate module for calculations
author: bgoncharuck
version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  
  # I don't want to publish this package, it is too small and uncompleted.
  int_datetime:
    path: ../int_datetime

  poll_availability:
    path: ../models/poll_availability
  users_repository:
    path: ../data/abstract/users_repository
  userpoll:
    path: ../data/abstract/userpoll
  pollbydate:
    path: ../data/abstract/pollbydate
