name: prophecy_bloc
description: prophecy_bloc
author: bgoncharuck
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  bloc: ^4.0.0
  equatable: ^1.2.0
  rxdart: ^0.24.1
